pointfreeco/swift-issue-reporting

- Sources/XCTestDynamicOverlay/XCTFail.swift
It should be easy to define failing helpers in modules that are built for release.
> Don't restrict helpers to DEBUG builds

- Sources/XCTestDynamicOverlay/Documentation.docc/GettingStarted.md
- Sources/XCTestDynamicOverlay/Documentation.docc/UnimplementedOverloads.md
- Sources/XCTestDynamicOverlay/Documentation.docc/XCTestDynamicOverlay.md
- Sources/XCTestDynamicOverlay/XCTUnimplemented.swift
- Tests/XCTestDynamicOverlayTests/TestHelpers.swift
- Tests/XCTestDynamicOverlayTests/XCTestDynamicOverlayTests.swift
Was investigating why TCA dependencies fail to compile in DocC and decided to sketch out some docs for this library.
While hiding away the overloads I realized we don't need the `Void`-returning ones. We can just check `Result` dynamically.
> DocC and XCTUnimplemented cleanup

- Sources/XCTestDynamicOverlay/Internal/RuntimeWarnings.swift
I copy-pasted the runtime warning code from TCA, which calls XCTFail from this library. We just should omit that recursive call entirely.
Fixes #18.
> Fix infinite loop

- Sources/XCTestDynamicOverlay/XCTUnimplemented.swift
Adds some calling context to `XCTUnimplemented` by printing the parameters passed along.
Could maybe take functionality/ergonomics even further in the future:
> Add context to unimplemented failure messages

- Sources/XCTestDynamicOverlay/XCTIsTesting.swift
The current check works fine for SPM packages, via Xcode, via `swift test`, and on Apple and non-Apple platforms, but it doesn't work for app hosts, which appear to configure the test runner via the environment.
> Make `_XCTIsTesting` check a bit more robust

- Sources/XCTestDynamicOverlay/XCTIsTesting.swift
This PR adds `if !os(WASI)` for the scopes where some of the Foundation classes don't work in SwiftWasm.
[Porting code from other platforms - Swift and WebAssembly](https://book.swiftwasm.org/getting-started/porting.html#swift-foundation-and-dispatch)
This fix is mainly for allowing CustomDump to work correctly, which I will also open the related pull request soon.
> Add `if !os(WASI)` for SwiftWasm

- .github/workflows/ci.yml
- .github/workflows/documentation.yml
- .github/workflows/format.yml
- README.md
This does the bare minimum to get docs generated on this repo. There's still more we can do to improve the docs, but we can worry about that later.
> Generate docs on CI

- Sources/XCTestDynamicOverlay/Internal/DefaultInitializable.swift
- Sources/XCTestDynamicOverlay/Internal/GeneratePlaceholder.swift
- Sources/XCTestDynamicOverlay/Unimplemented.swift
- Tests/XCTestDynamicOverlayTests/GeneratePlaceholderTests.swift
This PR allows `_generatePlaceholder()` to work with additional types. This is more of a proof of concept and I think it needs to be reworked after defining the desired behaviour of `_generatePlaceholder()`. I'm not attached to any of the naming or approach taken. I've structured things in a way that will hopefully make it easy to understand and discuss. 
Some notes:
There are a few ways of generating a placeholder:
- Identifying a know type and returning a placeholder value
```swift
if Result.self == Void.self { return () as? Result }
```
- Using an existing protocol that has a requirement that provides a placeholder value
```swift
(Result.self as? any RangeReplaceableCollection.Type)?.init() as? Result
(Result.self as? any AdditiveArithmetic.Type)?.zero as? Result
```
- Defining a new …
> Support more generated placeholder types

- README.md
- Sources/XCTestDynamicOverlay/Documentation.docc/GettingStarted.md
- Sources/XCTestDynamicOverlay/Documentation.docc/UnimplementedPlaceholder.md
- Sources/XCTestDynamicOverlay/Unimplemented.swift
- Tests/XCTestDynamicOverlayTests/TestHelpers.swift
This is an idea brought up by @tgrapperon. I had to remove a lot of `@_disfavoredOverload`s to get it to work, but I'm now wondering why they were there in the first place. Things seem to compile just fine without them.
> Support `unimplemented` as a "hole" for autoclosures

- Sources/XCTestDynamicOverlay/Internal/XCTCurrentTestCase.swift
- Tests/XCTestDynamicOverlayTests/CurrentTestCaseTests.swift
We need access to this to implement an XCTUnwrap helper for enums and case paths.
> Make XCTCurrentTestCase visible to SPI.

- Makefile
- Sources/XCTestDynamicOverlay/XCTFail.swift
- Tests/XCTestDynamicOverlayTests/HostAppDetectionTests.swift
This PR appends a warning message to the original failure message if `XCTFail` is called from the host app, while testing, but outside of a test. 
It deduces that the failure is originating from the main hosting app by:
- Checking that we're indeed testing.
- Checking that the `bundleIdentifier` is not the default one provided by `XCTest` (i.e. we're hosting tests with the main app)
- Checking that the call stack doesn't contain test-related frames (i.e. we're not running a test)
> Show a warning when some failure is generated outside of a test by the host app.

- Sources/XCTestDynamicOverlay/XCTFail.swift
- Tests/XCTestDynamicOverlayTests/HostAppDetectionTests.swift
Just a lil cleanup work from #48. Attempting to make it loud and actionable to prevent some of the confusion we're seeing.
> Finesse host application warning

- Sources/XCTestDynamicOverlay/XCTFail.swift
The way we detect app hosts triggers more often than we expected, especially in async tests, so let's make it sound a bit more informational instead of a loud warning that makes the false positive sound more definitive.
> Soften app host failure message

- .github/workflows/ci.yml
- Makefile
- README.md
- Sources/XCTestDynamicOverlay/Documentation.docc/GettingStarted.md
- Sources/XCTestDynamicOverlay/Documentation.docc/XCTestDynamicOverlay.md
- Sources/XCTestDynamicOverlay/Internal/RuntimeWarnings.swift
- Sources/XCTestDynamicOverlay/XCTFail.swift
Calling the dynamically loaded `XCTFail` in non-`DEBUG` builds is a no-op and so can lead people to believe their tests are passing when in reality nothing is actually happening. Let's start printing loud warnings in the console to let people know this is happening.
This is an example of what it looks like if no file/line is provided:
```
XCTFail: Unimplemented: f05 …
Defined at:
XCTestDynamicOverlayTests/TestHelpers.swift:71
Invoked with:
("", 42, 1.2, [1, 2], XCTestDynamicOverlayTests.User(id: DEADBEEF-DEAD-BEEF-DEAD-BEEFDEADBEEF))
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┉┅
┃ ⚠︎ Warning: This XCTFail was ignored
┃
┃ XCTFail was invoked in a non-DEBUG environment
┃ and so was ignored. Be sure to run tests with
┃ the DEBUG=1 flag set in order to dynamically
┃ load XCTFail. …
```
> Print warning in console when invoking XCFail from non-DEBUG

- .github/workflows/ci.yml
- Sources/XCTestDynamicOverlay/XCTFail.swift
- Tests/XCTestDynamicOverlayTests/XCTContextTests.swift
This allows us to provide APIs that thread the `file`/`line` through concurrent contexts that otherwise lose the stack.
> Add `XCTFailContext` task local

- .github/workflows/ci.yml
- Package.swift
- Tests/XCTestDynamicOverlayTests/GeneratePlaceholderTests.swift
- Tests/XCTestDynamicOverlayTests/UnimplementedTests.swift
- Tests/XCTestDynamicOverlayTests/XCTContextTests.swift
Skip tests where XCTExpectedFailure is used as this behavior is currently unimplemented on Windows and Linux (https://github.com/apple/swift-corelibs-xctest/issues/438)
> Add Windows CI

- .github/workflows/ci.yml
- Sources/XCTestDynamicOverlay/XCTFail.swift
Similar to the ObjC XCTest, prefer to delay load the XCTest runtime. This is likely to fail on release distributions as XCTest is a developer component. However, if it is available in the library search path on (non-Darwin) Unix or in `Path` on Windows, it will be used.
Windows does not (yet) ship a static XCTest library. On Linux, it is unclear whether the linkage is dynamic or static, so we perform a little trick. We pass `RTLD_NOLOAD` to `dlopen` which will get a handle to `libXCTest.so` if it is currently loaded in the address space but not load the library if not already there. In such a case, it will return `NULL`. In such a case, we resort to looking within the main binary (assuming that XCTest may have been statically linked).
For both platforms, if we do not find the symbol from …
> XCTestDynamicOverlay: prefer delay loading `XCTFail`

- Package.swift
- Sources/XCTestDynamicOverlay/Internal/GeneratePlaceholder.swift
- Sources/XCTestDynamicOverlay/XCTFail.swift
With concurrency warnings dialed up, this type can cause warnings to be emitted, but as a task local should be safe to pass along.
> Make `XCTestContext` sendable

- Makefile
- Sources/XCTestDynamicOverlay/XCTExpectFailure.swift
- Sources/XCTestDynamicOverlay/XCTFail.swift
- Tests/XCTestDynamicOverlayTests/GeneratePlaceholderTests.swift
- Tests/XCTestDynamicOverlayTests/TestHelpers.swift
- Tests/XCTestDynamicOverlayTests/UnimplementedTests.swift
- Tests/XCTestDynamicOverlayTests/XCTContextTests.swift
- Tests/XCTestDynamicOverlayTests/XCTExpectFailureTests.swift
- Tests/XCTestDynamicOverlayTests/XCTFailTests.swift
This PR takes the work @ZevEisenberg started with #59 and attempts to take it to the finish line. The changes I've made:
1. Limited `XCTExpectFailure` to Objective-C platforms (it's still [unavailable](https://github.com/apple/swift-corelibs-xctest/issues/438) elsewhere).
1. Finished implementing the official `XCTExpectFailure` signature, including `enabled`, `issueMatcher` and the continuation's return value.
1. Added the version that does not take a failing block.
> Add `XCTExpectFailure`

- Sources/XCTestDynamicOverlay/XCTFail.swift
SwiftWasm introduced its own WASI module awhile back, so we should import that instead of Glibc to avoid potential issues.
> Fix SwiftWasm Glibc import issue

- .github/workflows/ci.yml
- Sources/XCTestDynamicOverlay/XCTFail.swift
- Tests/XCTestDynamicOverlayTests/GeneratePlaceholderTests.swift
- Tests/XCTestDynamicOverlayTests/UnimplementedTests.swift
- Tests/XCTestDynamicOverlayTests/XCTContextTests.swift
While #76 attempted to fix an issue in a downstream package, there were other issues lurking. Let's see if we can get this package's Wasm CI to work, and see if the downstream package can build against this PR.
> Address more Wasm issues

- .github/workflows/ci.yml
`swiftwasm/swiftwasm-action` is now deprecated and replaced by `swiftwasm/setup-swiftwasm`. This change updates the CI workflow to use the new action.
> Use `swiftwasm/setup-swiftwasm` instead of `swiftwasm/swiftwasm-action`

- Sources/XCTestDynamicOverlay/Unimplemented.swift
A couple feature requests and pull requests have come in recently for `unimplemented`. While we consider `@DependencyClient` and `@DependencyEndpoint` to be a replacement for `unimplemented`, we still haven't communicated that in the source, so let's do so here via soft-deprecation.
> Soft-deprecate `unimplemented`

- .github/workflows/ci.yml
- Makefile
- Package@swift-6.0.swift
- Sources/XCTestDynamicOverlay/Internal/RuntimeWarnings.swift
- Sources/XCTestDynamicOverlay/Unimplemented.swift
- Sources/XCTestDynamicOverlay/XCTExpectFailure.swift
- Tests/XCTestDynamicOverlayTests/CurrentTestCaseTests.swift
- Tests/XCTestDynamicOverlayTests/GeneratePlaceholderTests.swift
- Tests/XCTestDynamicOverlayTests/TestHelpers.swift
We can drop Swift <5.9 now that the App Store requires Xcode 15 for submissions, and we can add 6.0 language mode to keep our concurrency story in check.
> Swift Language Support: Drop <5.9, Add 6.0

- Sources/IssueReporting/Internal/Warn.swift
Fix compile error on Linux:
```
❯ docker run --rm -v $PWD:/host -w /host swiftlang/swift@sha256:c0ba23ba9871be0552d48c5e98f363bf606858aedca11bf557bc0adde12bbc60 swift build
...
/host/Sources/IssueReporting/Internal/Warn.swift:9:25: error: reference to var 'stderr' is not concurrency-safe because it involves shared mutable state
7 | @usableFromInline
8 | func printError(_ message: String) {
9 |   fputs("\(message)\n", stderr)
|                         `- error: reference to var 'stderr' is not concurrency-safe because it involves shared mutable state
10 | }
11 | 
SwiftGlibc.stderr:1:12: note: var declared here
1 | public var stderr: UnsafeMutablePointer<FILE>!
|            `- note: var declared here
```
`swiftlang/swift@sha256:c0ba23ba9871be0552d48c5e98f363bf606858aedca11bf557bc0adde12bbc60 …
> Fix compile error Swift 6/Linux

- Package.swift
Our recent release introducing IssueReporting caused an unintended breakage due to the change of the package name. We can revert that change and save it for a future 2.0 release.
> Fix for backwards compatibility of package name.

- Package@swift-6.0.swift
Apply the fix from https://github.com/pointfreeco/swift-issue-reporting/pull/97 to `Package@swift-6.0.swift` as well.
> Rename package name in Package@swift-6.0.swift to match Package.swift.

- Sources/IssueReporting/Documentation.docc/Extensions/IssueReporter.breakpoint.md
- Sources/IssueReporting/Documentation.docc/Extensions/IssueReporter.fatalError.md
- Sources/IssueReporting/Documentation.docc/Extensions/IssueReporter.runtimeWarning.md
- Sources/IssueReporting/Internal/Deprecations.swift
- Sources/IssueReporting/IssueReporters/BreakpointReporter.swift
- Sources/IssueReporting/IssueReporters/FatalErrorReporter.swift
- Sources/IssueReporting/IssueReporters/RuntimeWarningReporter.swift
The big issue here is that `FatalErrorReporter` takes precedence in autocomplete over Swift's `fatalError` and is quite an annoyance when importing our library.
These probably should have never been prominent when the preferred spelling is `.fatalError`, etc.
This is a breaking bug fix change with fix-its.
> Underscore issue reporter type names

- Sources/XCTestDynamicOverlay/Internal/Deprecations.swift
- Tests/XCTestDynamicOverlayTests/TestHelpers.swift
- Tests/XCTestDynamicOverlayTests/UnimplementedTests.swift
> Fix regression: don't `fatalError` eagerly when calling deprecated `unimplemented` endpoints

- Sources/IssueReporting/Unimplemented.swift
In order to be able to construct and throw UnimplementedFailure as alternative solution to `unimplemented` placeholder in throws functions and closures. 
```swift
unimplemented("\(Self.self).count is unimplemented")
throw UnimplementedFailure(description: "\(Self.self).count is unimplemented")
```
> Implement public initializer for UnimplementedFailure

- Sources/IssueReporting/Internal/SwiftTesting.swift
- Sources/IssueReportingTestSupport/SwiftTesting.swift
- Tests/IssueReportingTests/SwiftTestingTests.swift
- Tests/IssueReportingTests/UnimplementedTests.swift
We should be calling to this more stable interface now that the messaging has been updated.
> Update `reportIssue` to call `Issue.record`

- Sources/IssueReporting/Documentation.docc/Extensions/Unimplemented.md
- Sources/IssueReporting/Unimplemented.swift
This adds `unimplemented` support for endpoints using typed throws.
> `unimplemented` support for typed throws

- Examples/ExamplesTests/SwiftTestingTests.swift
- Sources/XCTestDynamicOverlay/Internal/Deprecations.swift
- Tests/IssueReportingTests/UnimplementedTests.swift
- Tests/XCTestDynamicOverlayTests/TestHelpers.swift
When XCTestDynamicOverlay and IssueReporting are both imported into a file, the deprecated version takes precedence in certain situations, triggering a warning. This PR should address.
> Disfavor another `unimplemented` deprecation

- .github/workflows/ci.yml
- Examples/ExamplesTests/SwiftTestingTests.swift
- Examples/ExamplesTests/XCTestTests.swift
- Makefile
- Sources/IssueReporting/Internal/SwiftTesting.swift
- Sources/IssueReporting/TestContext.swift
- Sources/IssueReportingTestSupport/SwiftTesting.swift
- Tests/IssueReportingTests/SwiftTestingTests.swift
- Tests/IssueReportingTests/XCTestTests.swift
It can be useful to distinguish between tests in addition to knowing the test context, so let's surface some of that data.
One example use case, preventing global state from bleeding between tests in our Dependencies library: https://github.com/pointfreeco/swift-dependencies/pull/269
> Expose Testing test identifier from test context

- Sources/IssueReporting/Internal/SwiftTesting.swift
- Sources/IssueReporting/TestContext.swift
- Sources/IssueReportingTestSupport/SwiftTesting.swift
Test cases aren't externally identifiable at the moment, so if we leverage the current test's identity, we also need to know whether or not the test is parameterized.
> Add `Test.Case.isParameterized` to Testing context

- Sources/IssueReporting/TestContext.swift
We lost the `Equatable` conformance on `TestContext` with #125, so bringing it back.
> Make TestContext Equatable.

- Sources/IssueReporting/Internal/SwiftTesting.swift
- Sources/IssueReporting/TestContext.swift
- Sources/IssueReportingTestSupport/SwiftTesting.swift
> Revert #127

- .github/workflows/ci.yml
16 beta 6 has been removed from the image.
> Update CI to use the Xcode 16 release

- .github/workflows/ci.yml
- Sources/IssueReporting/ReportIssue.swift
- Sources/IssueReporting/WithExpectedIssue.swift
Address build issues seen building for library evolution mode, Xcode 16 - i.e. via `make build-for-library-evolution`.
> Address build issues occurring when building with Library Evolution support, Xcode 16

- Examples/Examples/ExamplesApp.swift
- Sources/IssueReporting/IssueReporters/RuntimeWarningReporter.swift
This came up in Slack today, but currently runtime warnings go into the void in previews because previews don't see `os_log`. So, if we detect we are in previews we can decide to log to the console instead:
> Print runtime warning in previews.

- Sources/IssueReporting/IssueReporter.swift
When integrating the latest versions into our app I noticed https://github.com/pointfreeco/swift-issue-reporting/issues/139. The fix here is the copy the default protocol extension implementation of `reportIssue(_:_:)` (the one that takes an error as a parameter) inside `_RuntimeWarningReporter` and add the `@_transparent` attribute.
Verified in my work project that this works as expected! Photos are below (ignore the `attributes` parameter, that comes from our wrapper code around this library but doesn't affect the result)
| Before | After |
|--------|--------|
| <img width="1129" alt="image" src="https://github.com/user-attachments/assets/7e493c85-b4c3-4746-aa92-50cd64286951"> | <img width="1365" alt="image" src="https://github.com/user-attachments/assets/59568d59-d525-4e73-930f-b3299999 …
> Add @_transparency attribute to reportIssue(_:_:) default implementation

- .github/workflows/ci.yml
- Sources/IssueReporting/Documentation.docc/Extensions/withErrorReporting.md
- Sources/IssueReporting/Documentation.docc/IssueReporting.md
- Sources/IssueReporting/ErrorReporting.swift
- Tests/IssueReportingTests/WithErrorReportingTests.swift
It's common to write the following boilerplate when working with code that can throw errors:
```swift
do {
try work()
} catch {
reportIssue(error)
}
```
Let's extract this pattern to a helper that can save at least some boilerplate:
```swift
withErrorReporting {
try work()
}
```
Or even make it a 1-liner in some cases:
```swift
withErrorReporting(catching: work)
```
> Add `withErrorReporting`

- .github/workflows/ci.yml
- Sources/IssueReporting/Documentation.docc/Extensions/withErrorReporting.md
- Sources/IssueReporting/Documentation.docc/Extensions/withIssueReporters.md
- Sources/IssueReporting/Documentation.docc/IssueReporting.md
- Sources/IssueReporting/ErrorReporting.swift
- Sources/IssueReporting/IssueReporter.swift
- Tests/IssueReportingTests/SwiftTestingTests.swift
- Tests/IssueReportingTests/UnimplementedTests.swift
- Tests/IssueReportingTests/WithErrorReportingTests.swift
Oversight when iterating on the APIs in #143. Added a test but wish we had `reasync` 😬
> Pass `message` along in async `withErrorReporting`

- .github/workflows/ci.yml
- README.md
- Sources/IssueReporting/Documentation.docc/Articles/GettingStarted.md
- Sources/IssueReporting/Documentation.docc/IssueReporting.md
Right now there is confusion on how to depend on this library because technically people need to use the old repository URL.
> Update installation instructions

- .github/workflows/ci.yml
- Examples/Examples.xcodeproj/project.pbxproj
- Examples/Examples/ExampleTrait.swift
- Examples/ExamplesTests/TraitTests.swift
- Package.swift
- Package@swift-6.0.swift
- Sources/IssueReporting/Internal/SwiftTesting.swift
- Sources/IssueReporting/TestContext.swift
- Sources/IssueReportingPackageSupport/_Test.swift
- Sources/IssueReportingTestSupport/SwiftTesting.swift
- Tests/XCTestDynamicOverlayTests/TestHelpers.swift
This PR adds dynamic support for Swift Testing's test traits.
We have libraries that work in Swift Testing, pre-Test Scoping traits, but it requires introspection of those traits. This PR allows introspection of these traits in a dynamic way, which is required by our Snapshot Testing library to support UI test targets: https://github.com/pointfreeco/swift-snapshot-testing/pull/975
> Test traits

- Sources/IssueReporting/ReportIssue.swift
- Tests/IssueReportingTests/SwiftTestingTests.swift
- Tests/IssueReportingTests/XCTestTests.swift
Localizing the coalescing logic so that we don't run the risk of forgetting it. Also added some tests.
> Issue context clean up

- Sources/IssueReportingTestSupport/SwiftTesting.swift
- Tests/IssueReportingTests/SwiftTestingTests.swift
It appears that Swift Testing will [crash](https://github.com/swiftlang/swift-testing/issues/1107) when recording an issue with an empty comment:
```swift
Issue.record("")  // 🛑
```
I think we should work around this problem for `reportIssue` since they are typically used in app code and so has a great chance of a custom message being crafted that may end up as an empty string.
> Fix empty message crash.

- Sources/IssueReporting/ErrorReporting.swift
Swift 5.10 has a strange bug that causes compilation to fail on Linux when `if compiler(>=6.0)` blocks are used:
* https://github.com/swiftlang/swift/issues/79285
**swift-issue-reporting** is impacted by this as reported in:
* #150
There is an existing workaround used in AHC:
*  https://github.com/swift-server/async-http-client/pull/810
This PR fixes the issue by using the workaround that involves changing white spaces around the impacted syntax.
> Fix Swift 5.10 toolchain issue on Linux builds
